using System;
using System.Collections.Generic;
using System.Text;

namespace OrmCodeGenLib
{
    public class OrmCodeDomGeneratorSettings
    {
        private bool _split = false;
        private string _entitySchemaDefClassNameSuffix = "SchemaDef";
        private string _baseClassNameSuffix = "Base";
        private string _partialAutoGeneratedFilePrefix = "AutoGenerated_";
        private OrmObjectGeneratorBehaviour _behaviour = OrmObjectGeneratorBehaviour.Objects;
        private LanguageSpecificHacks _languageSpecificHacks; 

        public bool IsPartial
        {
            get { return _behaviour == OrmObjectGeneratorBehaviour.PartialObjects || _split; }
        }

        public bool Split
        {
            get { return _split; }
            set { _split = value; }
        }

        public string EntitySchemaDefClassNameSuffix
        {
            get { return _entitySchemaDefClassNameSuffix; }
            set { _entitySchemaDefClassNameSuffix = value; }
        }

        public string BaseClassNameSuffix
        {
            get { return _baseClassNameSuffix; }
            set { _baseClassNameSuffix = value; }
        }

        public string PartialAutoGeneratedFilePrefix
        {
            get { return _partialAutoGeneratedFilePrefix; }
            set { _partialAutoGeneratedFilePrefix = value; }
        }

        public OrmObjectGeneratorBehaviour Behaviour
        {
            get { return _behaviour; }
            set { _behaviour = value; }
        }

        public LanguageSpecificHacks LanguageSpecificHacks
        {
            get { return _languageSpecificHacks; }
            set { _languageSpecificHacks = value; }
        }
    }

    public enum OrmObjectGeneratorBehaviour
    {
        Objects,
        PartialObjects,
        BaseObjects
    }
    [Flags]
    public enum LanguageSpecificHacks
    {
        None = 0,
        /// <summary>
        /// Generic члены производных классов требует наличия констрейтов
        /// </summary>
        DerivedGenericMembersRequireConstraits = 0x0001,
        MethodsInsteadParametrizedProperties = 0x0002,
        AddOptionsStrict = 0x0004,
        OptionsStrictOn = 0x0008,
        AddOptionsExplicit = 0x0010,
        OptionsExplicitOn = 0x0011,

        CSharp = MethodsInsteadParametrizedProperties,
        VisualBasic = DerivedGenericMembersRequireConstraits | AddOptionsExplicit | AddOptionsStrict | OptionsExplicitOn | OptionsStrictOn
    }

}
