<?xml version="1.0" encoding="utf-8"?>
<Database Name="TestDA" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=D:\depot_tfs\DAPerformance\DB\TestDA.mdf;Integrated Security=True" SettingsObjectName="DALinq.Properties.Settings" SettingsPropertyName="TestDAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_phone" Member="tbl_phones">
    <Type Name="tbl_phone">
      <Column Name="phone_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tbl_user_tbl_phone" Member="tbl_user" ThisKey="user_id" Type="tbl_user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_user" Member="tbl_users">
    <Type Name="tbl_user">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" IsDelayLoaded="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" IsDelayLoaded="true" />
      <Association Name="tbl_user_tbl_phone" Member="tbl_phones" OtherKey="user_id" Type="tbl_phone" />
    </Type>
  </Table>
</Database>