//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("TestDAModel", "FK_tbl_phone_tbl_user", "tbl_user", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TestDAModel.tbl_user), "tbl_phone", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TestDAModel.tbl_phone))]

// Original file name:
// Generation date: 21.03.2008 15:31:40
namespace TestDAModel
{
    
    /// <summary>
    /// There are no comments for TestDAEntities in the schema.
    /// </summary>
    public partial class TestDAEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new TestDAEntities object using the connection string found in the 'TestDAEntities' section of the application configuration file.
        /// </summary>
        public TestDAEntities() : 
                base("name=TestDAEntities", "TestDAEntities")
        {
        }
        /// <summary>
        /// Initialize a new TestDAEntities object.
        /// </summary>
        public TestDAEntities(string connectionString) : 
                base(connectionString, "TestDAEntities")
        {
        }
        /// <summary>
        /// Initialize a new TestDAEntities object.
        /// </summary>
        public TestDAEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TestDAEntities")
        {
        }
        /// <summary>
        /// There are no comments for tbl_phone in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<tbl_phone> tbl_phone
        {
            get
            {
                if ((this._tbl_phone == null))
                {
                    this._tbl_phone = base.CreateQuery<tbl_phone>("[tbl_phone]");
                }
                return this._tbl_phone;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tbl_phone> _tbl_phone;
        /// <summary>
        /// There are no comments for tbl_user in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<tbl_user> tbl_user
        {
            get
            {
                if ((this._tbl_user == null))
                {
                    this._tbl_user = base.CreateQuery<tbl_user>("[tbl_user]");
                }
                return this._tbl_user;
            }
        }
        private global::System.Data.Objects.ObjectQuery<tbl_user> _tbl_user;
        /// <summary>
        /// There are no comments for tbl_phone in the schema.
        /// </summary>
        public void AddTotbl_phone(tbl_phone tbl_phone)
        {
            base.AddObject("tbl_phone", tbl_phone);
        }
        /// <summary>
        /// There are no comments for tbl_user in the schema.
        /// </summary>
        public void AddTotbl_user(tbl_user tbl_user)
        {
            base.AddObject("tbl_user", tbl_user);
        }
    }
    /// <summary>
    /// There are no comments for TestDAModel.tbl_phone in the schema.
    /// </summary>
    /// <KeyProperties>
    /// phone_id
    /// user_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TestDAModel", Name="tbl_phone")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class tbl_phone : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tbl_phone object.
        /// </summary>
        /// <param name="phone_id">Initial value of phone_id.</param>
        /// <param name="user_id">Initial value of user_id.</param>
        public static tbl_phone Createtbl_phone(int phone_id, int user_id)
        {
            tbl_phone tbl_phone = new tbl_phone();
            tbl_phone.phone_id = phone_id;
            tbl_phone.user_id = user_id;
            return tbl_phone;
        }
        /// <summary>
        /// There are no comments for Property phone_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int phone_id
        {
            get
            {
                return this._phone_id;
            }
            set
            {
                this.Onphone_idChanging(value);
                this.ReportPropertyChanging("phone_id");
                this._phone_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("phone_id");
                this.Onphone_idChanged();
            }
        }
        private int _phone_id;
        partial void Onphone_idChanging(int value);
        partial void Onphone_idChanged();
        /// <summary>
        /// There are no comments for Property user_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this.ReportPropertyChanging("user_id");
                this._user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_id");
                this.Onuser_idChanged();
            }
        }
        private int _user_id;
        partial void Onuser_idChanging(int value);
        partial void Onuser_idChanged();
        /// <summary>
        /// There are no comments for Property phone_number in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_number
        {
            get
            {
                return this._phone_number;
            }
            set
            {
                this.Onphone_numberChanging(value);
                this.ReportPropertyChanging("phone_number");
                this._phone_number = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50);
                this.ReportPropertyChanged("phone_number");
                this.Onphone_numberChanged();
            }
        }
        private string _phone_number;
        partial void Onphone_numberChanging(string value);
        partial void Onphone_numberChanged();
        /// <summary>
        /// There are no comments for tbl_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TestDAModel", "FK_tbl_phone_tbl_user", "tbl_user")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public tbl_user tbl_user
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_user>("TestDAModel.FK_tbl_phone_tbl_user", "tbl_user").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_user>("TestDAModel.FK_tbl_phone_tbl_user", "tbl_user").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for tbl_user in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<tbl_user> tbl_userReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<tbl_user>("TestDAModel.FK_tbl_phone_tbl_user", "tbl_user");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<tbl_user>("TestDAModel.FK_tbl_phone_tbl_user", "tbl_user", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for TestDAModel.tbl_user in the schema.
    /// </summary>
    /// <KeyProperties>
    /// user_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="TestDAModel", Name="tbl_user")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class tbl_user : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new tbl_user object.
        /// </summary>
        /// <param name="user_id">Initial value of user_id.</param>
        public static tbl_user Createtbl_user(int user_id)
        {
            tbl_user tbl_user = new tbl_user();
            tbl_user.user_id = user_id;
            return tbl_user;
        }
        /// <summary>
        /// There are no comments for Property user_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id
        {
            get
            {
                return this._user_id;
            }
            set
            {
                this.Onuser_idChanging(value);
                this.ReportPropertyChanging("user_id");
                this._user_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("user_id");
                this.Onuser_idChanged();
            }
        }
        private int _user_id;
        partial void Onuser_idChanging(int value);
        partial void Onuser_idChanged();
        /// <summary>
        /// There are no comments for Property first_name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name
        {
            get
            {
                return this._first_name;
            }
            set
            {
                this.Onfirst_nameChanging(value);
                this.ReportPropertyChanging("first_name");
                this._first_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50);
                this.ReportPropertyChanged("first_name");
                this.Onfirst_nameChanged();
            }
        }
        private string _first_name;
        partial void Onfirst_nameChanging(string value);
        partial void Onfirst_nameChanged();
        /// <summary>
        /// There are no comments for Property last_name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name
        {
            get
            {
                return this._last_name;
            }
            set
            {
                this.Onlast_nameChanging(value);
                this.ReportPropertyChanging("last_name");
                this._last_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50);
                this.ReportPropertyChanged("last_name");
                this.Onlast_nameChanged();
            }
        }
        private string _last_name;
        partial void Onlast_nameChanging(string value);
        partial void Onlast_nameChanged();
        /// <summary>
        /// There are no comments for tbl_phone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("TestDAModel", "FK_tbl_phone_tbl_user", "tbl_phone")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<tbl_phone> tbl_phone
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<tbl_phone>("TestDAModel.FK_tbl_phone_tbl_user", "tbl_phone");
            }
        }
    }
}
