'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports Worm.Orm

Namespace test
	
	<Worm.Orm.EntityAttribute(GetType(test.Aspnet_Profile.Aspnet_ProfileSchemaDef), "1", EntityName:="Aspnet_Profile")>  _
	Public Class Aspnet_Profile
		Inherits Worm.Orm.OrmBase
		
		#Region "Private Fields"
		Private _userId As System.Guid
		
		Private _propertyNames As String
		
		Private _propertyValuesString As String
		
		Private _propertyValuesBinary() As Byte
		
		Private _lastUpdatedDate As Date
		#End Region
		
		#Region "Constructors"
		Public Sub New()
			MyBase.New
		End Sub
		
		Public Sub New(ByVal id As Integer, ByVal cache As Worm.Orm.OrmCacheBase, ByVal schema As Worm.Orm.OrmSchemaBase)
			MyBase.New(id, cache, schema)
		End Sub
		#End Region
		
		#Region "Description Properties"
		<Worm.Orm.ColumnAttribute("UserId", Worm.Orm.Field2DbRelations.PK)>  _
		Public Overridable Property UserId() As System.Guid
			Get
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(true, "UserId")
					Return Me._userId
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Get
			Set
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(false, "UserId")
					Me._userId = value
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Set
		End Property
		
		<Worm.Orm.ColumnAttribute("PropertyNames", Worm.Orm.Field2DbRelations.None)>  _
		Public Overridable Property PropertyNames() As String
			Get
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(true, "PropertyNames")
					Return Me._propertyNames
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Get
			Set
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(false, "PropertyNames")
					Me._propertyNames = value
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Set
		End Property
		
		<Worm.Orm.ColumnAttribute("PropertyValuesString", Worm.Orm.Field2DbRelations.None)>  _
		Public Overridable Property PropertyValuesString() As String
			Get
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(true, "PropertyValuesString")
					Return Me._propertyValuesString
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Get
			Set
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(false, "PropertyValuesString")
					Me._propertyValuesString = value
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Set
		End Property
		
		<Worm.Orm.ColumnAttribute("PropertyValuesBinary", Worm.Orm.Field2DbRelations.None)>  _
		Public Overridable Property PropertyValuesBinary() As Byte()
			Get
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(true, "PropertyValuesBinary")
					Return Me._propertyValuesBinary
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Get
			Set
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(false, "PropertyValuesBinary")
					Me._propertyValuesBinary = value
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Set
		End Property
		
		<Worm.Orm.ColumnAttribute("LastUpdatedDate", Worm.Orm.Field2DbRelations.None)>  _
		Public Overridable Property LastUpdatedDate() As Date
			Get
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(true, "LastUpdatedDate")
					Return Me._lastUpdatedDate
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Get
			Set
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(false, "LastUpdatedDate")
					Me._lastUpdatedDate = value
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Set
		End Property
		#End Region
		
		#Region "Static members"
		'''<summary>
		'''Метод копирует (потоко-небезопасно) значения полей одного объекта в другой
		'''</summary>
		Protected Shared Sub CopyAspnet_Profile(ByVal from As test.Aspnet_Profile, ByVal [to] As test.Aspnet_Profile)
			[to]._userId = from._userId
			[to]._propertyNames = from._propertyNames
			[to]._propertyValuesString = from._propertyValuesString
			[to]._propertyValuesBinary = from._propertyValuesBinary
			[to]._lastUpdatedDate = from._lastUpdatedDate
		End Sub
		#End Region
		
		Protected Overrides Sub CopyBody(ByVal from As Worm.Orm.OrmBase, ByVal [to] As Worm.Orm.OrmBase)
			test.Aspnet_Profile.CopyAspnet_Profile(CType(from,test.Aspnet_Profile), CType([to],test.Aspnet_Profile))
		End Sub
		
		Public Overloads Overrides Function CreateSortComparer(Of T As  {Worm.Orm.OrmBase, New})(ByVal sort As String, ByVal sortType As Worm.Orm.SortType) As System.Collections.Generic.IComparer(Of T)
			Throw New System.NotImplementedException("The method or operation is not implemented.")
		End Function
		
		Public Overloads Overrides Function CreateSortComparer(ByVal sort As String, ByVal sortType As Worm.Orm.SortType) As System.Collections.IComparer
			Throw New System.NotImplementedException("The method or operation is not implemented.")
		End Function
		
		Public Overrides Sub SetValue(ByVal pi As System.Reflection.PropertyInfo, ByVal c As Worm.Orm.ColumnAttribute, ByVal value As Object)
			If (c.FieldName = "UserId") Then
				Me._userId = CType(value,System.Guid)
				Return
			End If
			If (c.FieldName = "PropertyNames") Then
				Me._propertyNames = CType(value,String)
				Return
			End If
			If (c.FieldName = "PropertyValuesString") Then
				Me._propertyValuesString = CType(value,String)
				Return
			End If
			If (c.FieldName = "PropertyValuesBinary") Then
				Me._propertyValuesBinary = CType(value,Byte())
				Return
			End If
			If (c.FieldName = "LastUpdatedDate") Then
				Me._lastUpdatedDate = CType(value,Date)
				Return
			End If
			MyBase.SetValue(pi, c, value)
		End Sub
		
		Protected Overrides Function GetNew() As Worm.Orm.OrmBase
			Return New test.Aspnet_Profile(Me.Identifier, Me.OrmCache, Me.OrmSchema)
		End Function
		
		#Region "Nested Types"
		Public Class Aspnet_ProfileSchemaDef
			Implements Worm.Orm.IOrmObjectSchema, Worm.Orm.IOrmSchemaInit
			
			#Region "Private Fields"
			Private _idx As Worm.Orm.OrmObjectIndex
			
			Private _tables() As Worm.Orm.OrmTable
			
			Private _forTablesLock As Object = New Object
			
			Private _m2mRelations() As Worm.Orm.M2MRelation
			
			Private _forM2MRelationsLock As Object = New Object
			
			Private _forIdxLock As Object = New Object
			
			Protected _schema As Worm.Orm.OrmSchemaBase
			
			Protected _entityType As System.Type
			#End Region
			
			#Region "Description Properties"
			Public Overridable ReadOnly Property IsExternalSort(ByVal sort As String) As Boolean Implements Worm.Orm.IOrmObjectSchema.IsExternalSort
				Get
					Return false
				End Get
			End Property
			#End Region
			
			Protected Overridable Function GetTypeMainTable(ByVal type As System.Type) As Worm.Orm.OrmTable
				Dim tables() As Worm.Orm.OrmTable
				tables = CType(Me._schema,Worm.Orm.IDbSchema).GetTables(type)
				Return CType(tables.GetValue(0),Worm.Orm.OrmTable)
			End Function
			
			#Region "Base type related members"
			Public Overridable Function GetTables() As Worm.Orm.OrmTable() Implements Worm.Orm.IOrmObjectSchema.GetTables
				If (Me._tables Is Nothing) Then
					Dim lockCachedExpression_f8031ba0522942c4b326aad70418eefd As Object = Me._forTablesLock
					System.Threading.Monitor.Enter(lockCachedExpression_f8031ba0522942c4b326aad70418eefd)
					Try 
						If (Me._tables Is Nothing) Then
							Me._tables = New Worm.Orm.OrmTable() {New Worm.Orm.OrmTable("[dbo].[aspnet_Profile]")}
						End If
					Finally
						System.Threading.Monitor.Exit(lockCachedExpression_f8031ba0522942c4b326aad70418eefd)
					End Try
				End If
				Return Me._tables
			End Function
			
			Protected Overridable Function GetTable(ByVal tbl As test.Aspnet_Profile.Aspnet_ProfileSchemaDef.TablesLink) As Worm.Orm.OrmTable
				Return CType(Me.GetTables.GetValue(CType(tbl,Integer)),Worm.Orm.OrmTable)
			End Function
			
			Public Overridable Function ChangeValueType(ByVal c As Worm.Orm.ColumnAttribute, ByVal value As Object, ByRef newvalue As Object) As Boolean Implements Worm.Orm.IOrmObjectSchema.ChangeValueType
				newvalue = value
				Return false
			End Function
			
			Public Overridable Function ExternalSort(ByVal sort As String, ByVal sortType As Worm.Orm.SortType, ByVal objs As System.Collections.IList) As System.Collections.IList Implements Worm.Orm.IOrmObjectSchema.ExternalSort
				Return objs
			End Function
			
			Public Overridable Function GetJoins(ByVal left As Worm.Orm.OrmTable, ByVal right As Worm.Orm.OrmTable) As Worm.Orm.OrmJoin Implements Worm.Orm.IOrmObjectSchema.GetJoins
				Return CType(Nothing, Worm.Orm.OrmJoin)
			End Function
			
			Public Overridable Function GetSuppressedColumns() As Worm.Orm.ColumnAttribute() Implements Worm.Orm.IOrmObjectSchema.GetSuppressedColumns
				Return New Worm.Orm.ColumnAttribute(-1) {}
			End Function
			
			Public Overridable Function GetFilter(ByVal filter_info As Object) As Worm.Orm.IOrmFilter Implements Worm.Orm.IOrmObjectSchema.GetFilter
				Return Nothing
			End Function
			
			Public Overridable Function MapSort2FieldName(ByVal sort As String) As String Implements Worm.Orm.IOrmObjectSchema.MapSort2FieldName
				Return Nothing
			End Function
			
			Public Overridable Function GetM2MRelations() As Worm.Orm.M2MRelation() Implements Worm.Orm.IOrmObjectSchema.GetM2MRelations
				If (Me._m2mRelations Is Nothing) Then
					Dim lockCachedExpression_d44db3dbfa1342aca03d406e5706b629 As Object = Me._forM2MRelationsLock
					System.Threading.Monitor.Enter(lockCachedExpression_d44db3dbfa1342aca03d406e5706b629)
					Try 
						If (Me._m2mRelations Is Nothing) Then
							Me._m2mRelations = New Worm.Orm.M2MRelation(-1) {}
						End If
					Finally
						System.Threading.Monitor.Exit(lockCachedExpression_d44db3dbfa1342aca03d406e5706b629)
					End Try
				End If
				Return Me._m2mRelations
			End Function
			
			Public Overridable Function GetFieldColumnMap() As Worm.Orm.Collections.IndexedCollection(Of String, Worm.Orm.MapField2Column) Implements Worm.Orm.IOrmObjectSchema.GetFieldColumnMap
				If (Me._idx Is Nothing) Then
					Dim lockCachedExpression_4d62606b3690484a89eb297583ce0d92 As Object = Me._forIdxLock
					System.Threading.Monitor.Enter(lockCachedExpression_4d62606b3690484a89eb297583ce0d92)
					Try 
						If (Me._idx Is Nothing) Then
							Dim idx As Worm.Orm.OrmObjectIndex = New Worm.Orm.OrmObjectIndex
							idx.Add(New Worm.Orm.MapField2Column("UserId", "UserId", Me.GetTable(test.Aspnet_Profile.Aspnet_ProfileSchemaDef.TablesLink.tbldboaspnet_Profile)))
							idx.Add(New Worm.Orm.MapField2Column("PropertyNames", "PropertyNames", Me.GetTable(test.Aspnet_Profile.Aspnet_ProfileSchemaDef.TablesLink.tbldboaspnet_Profile)))
							idx.Add(New Worm.Orm.MapField2Column("PropertyValuesString", "PropertyValuesString", Me.GetTable(test.Aspnet_Profile.Aspnet_ProfileSchemaDef.TablesLink.tbldboaspnet_Profile)))
							idx.Add(New Worm.Orm.MapField2Column("PropertyValuesBinary", "PropertyValuesBinary", Me.GetTable(test.Aspnet_Profile.Aspnet_ProfileSchemaDef.TablesLink.tbldboaspnet_Profile)))
							idx.Add(New Worm.Orm.MapField2Column("LastUpdatedDate", "LastUpdatedDate", Me.GetTable(test.Aspnet_Profile.Aspnet_ProfileSchemaDef.TablesLink.tbldboaspnet_Profile)))
							Me._idx = idx
						End If
					Finally
						System.Threading.Monitor.Exit(lockCachedExpression_4d62606b3690484a89eb297583ce0d92)
					End Try
				End If
				Return Me._idx
			End Function
			#End Region
			
			Public Overridable Sub GetSchema(ByVal schema As Worm.Orm.OrmSchemaBase, ByVal t As System.Type) Implements Worm.Orm.IOrmSchemaInit.GetSchema
				Me._schema = schema
				Me._entityType = t
			End Sub
			
			#Region "Nested Types"
			Public Enum TablesLink
				
				#Region "Private Fields"
				tbldboaspnet_Profile = 0
				#End Region
			End Enum
			#End Region
		End Class
		#End Region
	End Class
End Namespace
