'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports Worm.Orm

Namespace test
	
	<Worm.Orm.EntityAttribute(GetType(test.Ent1.Ent1SchemaDef), "1", EntityName:="Ent1")>  _
	Public Class Ent1
		Inherits Worm.Orm.OrmBase
		
		#Region "Private Fields"
		Private _id As Integer
		#End Region
		
		#Region "Constructors"
		Public Sub New()
			MyBase.New
		End Sub
		
		Public Sub New(ByVal id As Integer, ByVal cache As Worm.Orm.OrmCacheBase, ByVal schema As Worm.Orm.OrmSchemaBase)
			MyBase.New(id, cache, schema)
		End Sub
		#End Region
		
		#Region "Description Properties"
		<Worm.Orm.ColumnAttribute("Id", Worm.Orm.Field2DbRelations.PK)>  _
		Public Overridable Property Id() As Integer
			Get
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(true, "Id")
					Return Me._id
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Get
			Set
				Dim syncHelper As System.IDisposable
				syncHelper = Nothing
				Try 
					syncHelper = Me.SyncHelper(false, "Id")
					Me._id = value
				Finally
					If (Not (syncHelper) Is Nothing) Then
						CType(syncHelper,System.IDisposable).Dispose
					End If
				End Try
			End Set
		End Property
		#End Region
		
		#Region "Static members"
		'''<summary>
		'''Метод копирует (потоко-небезопасно) значения полей одного объекта в другой
		'''</summary>
		Protected Shared Sub CopyEnt1(ByVal from As test.Ent1, ByVal [to] As test.Ent1)
			[to]._id = from._id
		End Sub
		#End Region
		
		Protected Overrides Sub CopyBody(ByVal from As Worm.Orm.OrmBase, ByVal [to] As Worm.Orm.OrmBase)
			test.Ent1.CopyEnt1(CType(from,test.Ent1), CType([to],test.Ent1))
		End Sub
		
		Public Overloads Overrides Function CreateSortComparer(Of T As  {Worm.Orm.OrmBase, New})(ByVal sort As String, ByVal sortType As Worm.Orm.SortType) As System.Collections.Generic.IComparer(Of T)
			Throw New System.NotImplementedException("The method or operation is not implemented.")
		End Function
		
		Public Overloads Overrides Function CreateSortComparer(ByVal sort As String, ByVal sortType As Worm.Orm.SortType) As System.Collections.IComparer
			Throw New System.NotImplementedException("The method or operation is not implemented.")
		End Function
		
		Public Overrides Sub SetValue(ByVal pi As System.Reflection.PropertyInfo, ByVal c As Worm.Orm.ColumnAttribute, ByVal value As Object)
			If (c.FieldName = "Id") Then
				Me._id = CType(value,Integer)
				Return
			End If
			MyBase.SetValue(pi, c, value)
		End Sub
		
		Protected Overrides Function GetNew() As Worm.Orm.OrmBase
			Return New test.Ent1(Me.Identifier, Me.OrmCache, Me.OrmSchema)
		End Function
		
		#Region "Nested Types"
		Public Class Ent1SchemaDef
			Implements Worm.Orm.IOrmObjectSchema, Worm.Orm.IOrmSchemaInit
			
			#Region "Private Fields"
			Private _idx As Worm.Orm.OrmObjectIndex
			
			Private _tables() As Worm.Orm.OrmTable
			
			Private _forTablesLock As Object = New Object
			
			Private _m2mRelations() As Worm.Orm.M2MRelation
			
			Private _forM2MRelationsLock As Object = New Object
			
			Private _forIdxLock As Object = New Object
			
			Protected _schema As Worm.Orm.OrmSchemaBase
			
			Protected _entityType As System.Type
			#End Region
			
			#Region "Description Properties"
			Public Overridable ReadOnly Property IsExternalSort(ByVal sort As String) As Boolean Implements Worm.Orm.IOrmObjectSchema.IsExternalSort
				Get
					Return false
				End Get
			End Property
			#End Region
			
			Protected Overridable Function GetTypeMainTable(ByVal type As System.Type) As Worm.Orm.OrmTable
				Dim tables() As Worm.Orm.OrmTable
				tables = CType(Me._schema,Worm.Orm.IDbSchema).GetTables(type)
				Return CType(tables.GetValue(0),Worm.Orm.OrmTable)
			End Function
			
			#Region "Base type related members"
			Public Overridable Function GetTables() As Worm.Orm.OrmTable() Implements Worm.Orm.IOrmObjectSchema.GetTables
				If (Me._tables Is Nothing) Then
					Dim lockCachedExpression_aa90f23a302d4ae2b3c8a272185cbdc7 As Object = Me._forTablesLock
					System.Threading.Monitor.Enter(lockCachedExpression_aa90f23a302d4ae2b3c8a272185cbdc7)
					Try 
						If (Me._tables Is Nothing) Then
							Me._tables = New Worm.Orm.OrmTable() {New Worm.Orm.OrmTable("[dbo].[ent1]")}
						End If
					Finally
						System.Threading.Monitor.Exit(lockCachedExpression_aa90f23a302d4ae2b3c8a272185cbdc7)
					End Try
				End If
				Return Me._tables
			End Function
			
			Protected Overridable Function GetTable(ByVal tbl As test.Ent1.Ent1SchemaDef.TablesLink) As Worm.Orm.OrmTable
				Return CType(Me.GetTables.GetValue(CType(tbl,Integer)),Worm.Orm.OrmTable)
			End Function
			
			Public Overridable Function ChangeValueType(ByVal c As Worm.Orm.ColumnAttribute, ByVal value As Object, ByRef newvalue As Object) As Boolean Implements Worm.Orm.IOrmObjectSchema.ChangeValueType
				newvalue = value
				Return false
			End Function
			
			Public Overridable Function ExternalSort(ByVal sort As String, ByVal sortType As Worm.Orm.SortType, ByVal objs As System.Collections.IList) As System.Collections.IList Implements Worm.Orm.IOrmObjectSchema.ExternalSort
				Return objs
			End Function
			
			Public Overridable Function GetJoins(ByVal left As Worm.Orm.OrmTable, ByVal right As Worm.Orm.OrmTable) As Worm.Orm.OrmJoin Implements Worm.Orm.IOrmObjectSchema.GetJoins
				Return CType(Nothing, Worm.Orm.OrmJoin)
			End Function
			
			Public Overridable Function GetSuppressedColumns() As Worm.Orm.ColumnAttribute() Implements Worm.Orm.IOrmObjectSchema.GetSuppressedColumns
				Return New Worm.Orm.ColumnAttribute(-1) {}
			End Function
			
			Public Overridable Function GetFilter(ByVal filter_info As Object) As Worm.Orm.IOrmFilter Implements Worm.Orm.IOrmObjectSchema.GetFilter
				Return Nothing
			End Function
			
			Public Overridable Function MapSort2FieldName(ByVal sort As String) As String Implements Worm.Orm.IOrmObjectSchema.MapSort2FieldName
				Return Nothing
			End Function
			
			Public Overridable Function GetM2MRelations() As Worm.Orm.M2MRelation() Implements Worm.Orm.IOrmObjectSchema.GetM2MRelations
				If (Me._m2mRelations Is Nothing) Then
					Dim lockCachedExpression_a5433b2105c348d18a87c565b1bb4a7f As Object = Me._forM2MRelationsLock
					System.Threading.Monitor.Enter(lockCachedExpression_a5433b2105c348d18a87c565b1bb4a7f)
					Try 
						If (Me._m2mRelations Is Nothing) Then
							Me._m2mRelations = New Worm.Orm.M2MRelation() {New Worm.Orm.M2MRelation(Me._schema.GetTypeByEntityName("Ent2"), CType(Me._schema,Worm.Orm.IDbSchema).GetSharedTable("[dbo].[1to2]"), "ent2_id", false, New System.Data.Common.DataTableMapping, CType(Nothing,System.Type))}
						End If
					Finally
						System.Threading.Monitor.Exit(lockCachedExpression_a5433b2105c348d18a87c565b1bb4a7f)
					End Try
				End If
				Return Me._m2mRelations
			End Function
			
			Public Overridable Function GetFieldColumnMap() As Worm.Orm.Collections.IndexedCollection(Of String, Worm.Orm.MapField2Column) Implements Worm.Orm.IOrmObjectSchema.GetFieldColumnMap
				If (Me._idx Is Nothing) Then
					Dim lockCachedExpression_c646d1b0b64b4e3589bf19424c01f0c6 As Object = Me._forIdxLock
					System.Threading.Monitor.Enter(lockCachedExpression_c646d1b0b64b4e3589bf19424c01f0c6)
					Try 
						If (Me._idx Is Nothing) Then
							Dim idx As Worm.Orm.OrmObjectIndex = New Worm.Orm.OrmObjectIndex
							idx.Add(New Worm.Orm.MapField2Column("Id", "id", Me.GetTable(test.Ent1.Ent1SchemaDef.TablesLink.tbldboent1)))
							Me._idx = idx
						End If
					Finally
						System.Threading.Monitor.Exit(lockCachedExpression_c646d1b0b64b4e3589bf19424c01f0c6)
					End Try
				End If
				Return Me._idx
			End Function
			#End Region
			
			Public Overridable Sub GetSchema(ByVal schema As Worm.Orm.OrmSchemaBase, ByVal t As System.Type) Implements Worm.Orm.IOrmSchemaInit.GetSchema
				Me._schema = schema
				Me._entityType = t
			End Sub
			
			#Region "Nested Types"
			Public Enum TablesLink
				
				#Region "Private Fields"
				tbldboent1 = 0
				#End Region
			End Enum
			#End Region
		End Class
		#End Region
	End Class
End Namespace
