'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.20506.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("32609e26-6e8d-493f-8ce6-d9b912501665"),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("wormtestModel", "FK_Table10_Table1", "Table1", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(efTable1), "Table10", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(efTable10)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("wormtestModel", "FK_Table2_Table2", "Table1", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(efTable1), "Table2", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(efTable2)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("wormtestModel", "FK_Tables1to3Relation_Table1", "Table1", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(efTable1), "Tables1to3Relation", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(efTables1to3Relation)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("wormtestModel", "FK_Tables1to3Relation_Table3", "Table3", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(efTable3), "Tables1to3Relation", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(efTables1to3Relation)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("wormtestModel", "FK_Table_Table2", "Table2", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(efTable2), "Table", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(efTable))> 

'Original file name:
'Generation date: 7/21/2009 10:28:12 AM
'''<summary>
'''There are no comments for wormtestEntities in the schema.
'''</summary>
Partial Public Class wormtestEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new wormtestEntities object using the connection string found in the 'wormtestEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=wormtestEntities", "wormtestEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new wormtestEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "wormtestEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new wormtestEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "wormtestEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for efTable1Set in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property efTable1Set() As Global.System.Data.Objects.ObjectQuery(Of efTable1)
        Get
            If (Me._efTable1Set Is Nothing) Then
                Me._efTable1Set = MyBase.CreateQuery(Of efTable1)("[efTable1Set]")
            End If
            Return Me._efTable1Set
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _efTable1Set As Global.System.Data.Objects.ObjectQuery(Of efTable1)
    '''<summary>
    '''There are no comments for efTable10Set in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property efTable10Set() As Global.System.Data.Objects.ObjectQuery(Of efTable10)
        Get
            If (Me._efTable10Set Is Nothing) Then
                Me._efTable10Set = MyBase.CreateQuery(Of efTable10)("[efTable10Set]")
            End If
            Return Me._efTable10Set
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _efTable10Set As Global.System.Data.Objects.ObjectQuery(Of efTable10)
    '''<summary>
    '''There are no comments for efTable2Set in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property efTable2Set() As Global.System.Data.Objects.ObjectQuery(Of efTable2)
        Get
            If (Me._efTable2Set Is Nothing) Then
                Me._efTable2Set = MyBase.CreateQuery(Of efTable2)("[efTable2Set]")
            End If
            Return Me._efTable2Set
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _efTable2Set As Global.System.Data.Objects.ObjectQuery(Of efTable2)
    '''<summary>
    '''There are no comments for efTable3Set in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property efTable3Set() As Global.System.Data.Objects.ObjectQuery(Of efTable3)
        Get
            If (Me._efTable3Set Is Nothing) Then
                Me._efTable3Set = MyBase.CreateQuery(Of efTable3)("[efTable3Set]")
            End If
            Return Me._efTable3Set
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _efTable3Set As Global.System.Data.Objects.ObjectQuery(Of efTable3)
    '''<summary>
    '''There are no comments for efTables1to3RelationSet in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property efTables1to3RelationSet() As Global.System.Data.Objects.ObjectQuery(Of efTables1to3Relation)
        Get
            If (Me._efTables1to3RelationSet Is Nothing) Then
                Me._efTables1to3RelationSet = MyBase.CreateQuery(Of efTables1to3Relation)("[efTables1to3RelationSet]")
            End If
            Return Me._efTables1to3RelationSet
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _efTables1to3RelationSet As Global.System.Data.Objects.ObjectQuery(Of efTables1to3Relation)
    '''<summary>
    '''There are no comments for efTableSet in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property efTableSet() As Global.System.Data.Objects.ObjectQuery(Of efTable)
        Get
            If (Me._efTableSet Is Nothing) Then
                Me._efTableSet = MyBase.CreateQuery(Of efTable)("[efTableSet]")
            End If
            Return Me._efTableSet
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _efTableSet As Global.System.Data.Objects.ObjectQuery(Of efTable)
    '''<summary>
    '''There are no comments for efTable1Set in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToefTable1Set(ByVal efTable1 As efTable1)
        MyBase.AddObject("efTable1Set", efTable1)
    End Sub
    '''<summary>
    '''There are no comments for efTable10Set in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToefTable10Set(ByVal efTable10 As efTable10)
        MyBase.AddObject("efTable10Set", efTable10)
    End Sub
    '''<summary>
    '''There are no comments for efTable2Set in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToefTable2Set(ByVal efTable2 As efTable2)
        MyBase.AddObject("efTable2Set", efTable2)
    End Sub
    '''<summary>
    '''There are no comments for efTable3Set in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToefTable3Set(ByVal efTable3 As efTable3)
        MyBase.AddObject("efTable3Set", efTable3)
    End Sub
    '''<summary>
    '''There are no comments for efTables1to3RelationSet in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToefTables1to3RelationSet(ByVal efTables1to3Relation As efTables1to3Relation)
        MyBase.AddObject("efTables1to3RelationSet", efTables1to3Relation)
    End Sub
    '''<summary>
    '''There are no comments for efTableSet in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToefTableSet(ByVal efTable As efTable)
        MyBase.AddObject("efTableSet", efTable)
    End Sub
End Class
'''<summary>
'''There are no comments for wormtestModel.efTable1 in the schema.
'''</summary>
'''<KeyProperties>
'''id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="wormtestModel", Name:="efTable1"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class efTable1
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new efTable1 object.
    '''</summary>
    '''<param name="id">Initial value of id.</param>
    '''<param name="dt">Initial value of dt.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateefTable1(ByVal id As Integer, ByVal dt As Date) As efTable1
        Dim efTable1 As efTable1 = New efTable1()
        efTable1.id = id
        efTable1.dt = dt
        Return efTable1
    End Function
    '''<summary>
    '''There are no comments for property id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property id() As Integer
        Get
            Return Me._id
        End Get
        Set
            Me.OnidChanging(value)
            Me.ReportPropertyChanging("id")
            Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("id")
            Me.OnidChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _id As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanged()
        End Sub
    '''<summary>
    '''There are no comments for property name in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property name() As String
        Get
            Return Me._name
        End Get
        Set
            Me.OnnameChanging(value)
            Me.ReportPropertyChanging("name")
            Me._name = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("name")
            Me.OnnameChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _name As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnameChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnameChanged()
        End Sub
    '''<summary>
    '''There are no comments for property code in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property code() As Global.System.Nullable(Of Integer)
        Get
            Return Me._code
        End Get
        Set
            Me.OncodeChanging(value)
            Me.ReportPropertyChanging("code")
            Me._code = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("code")
            Me.OncodeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _code As Global.System.Nullable(Of Integer)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OncodeChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OncodeChanged()
        End Sub
    '''<summary>
    '''There are no comments for property enum in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property [enum]() As Global.System.Nullable(Of Byte)
        Get
            Return Me._enum
        End Get
        Set
            Me.OnenumChanging(value)
            Me.ReportPropertyChanging("enum")
            Me._enum = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("enum")
            Me.OnenumChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _enum As Global.System.Nullable(Of Byte)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnenumChanging(ByVal value As Global.System.Nullable(Of Byte))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnenumChanged()
        End Sub
    '''<summary>
    '''There are no comments for property enum_str in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property enum_str() As String
        Get
            Return Me._enum_str
        End Get
        Set
            Me.Onenum_strChanging(value)
            Me.ReportPropertyChanging("enum_str")
            Me._enum_str = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("enum_str")
            Me.Onenum_strChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _enum_str As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onenum_strChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onenum_strChanged()
        End Sub
    '''<summary>
    '''There are no comments for property dt in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property dt() As Date
        Get
            Return Me._dt
        End Get
        Set
            Me.OndtChanging(value)
            Me.ReportPropertyChanging("dt")
            Me._dt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("dt")
            Me.OndtChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _dt As Date
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OndtChanging(ByVal value As Date)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OndtChanged()
        End Sub
    '''<summary>
    '''There are no comments for Table10 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Table10_Table1", "Table10"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table10() As Global.System.Data.Objects.DataClasses.EntityCollection(Of efTable10)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of efTable10)("wormtestModel.FK_Table10_Table1", "Table10")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of efTable10)("wormtestModel.FK_Table10_Table1", "Table10", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table2 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Table2_Table2", "Table2"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table2() As Global.System.Data.Objects.DataClasses.EntityCollection(Of efTable2)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of efTable2)("wormtestModel.FK_Table2_Table2", "Table2")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of efTable2)("wormtestModel.FK_Table2_Table2", "Table2", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Tables1to3Relation in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Tables1to3Relation_Table1", "Tables1to3Relation"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Tables1to3Relation() As Global.System.Data.Objects.DataClasses.EntityCollection(Of efTables1to3Relation)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of efTables1to3Relation)("wormtestModel.FK_Tables1to3Relation_Table1", "Tables1to3Relation")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of efTables1to3Relation)("wormtestModel.FK_Tables1to3Relation_Table1", "Tables1to3Relation", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for wormtestModel.efTable10 in the schema.
'''</summary>
'''<KeyProperties>
'''id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="wormtestModel", Name:="efTable10"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class efTable10
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new efTable10 object.
    '''</summary>
    '''<param name="id">Initial value of id.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateefTable10(ByVal id As Integer) As efTable10
        Dim efTable10 As efTable10 = New efTable10()
        efTable10.id = id
        Return efTable10
    End Function
    '''<summary>
    '''There are no comments for property id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property id() As Integer
        Get
            Return Me._id
        End Get
        Set
            Me.OnidChanging(value)
            Me.ReportPropertyChanging("id")
            Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("id")
            Me.OnidChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _id As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanged()
        End Sub
    '''<summary>
    '''There are no comments for Table1 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Table10_Table1", "Table1"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table1() As efTable1
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Table10_Table1", "Table1").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Table10_Table1", "Table1").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table1 in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table1Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of efTable1)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Table10_Table1", "Table1")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of efTable1)("wormtestModel.FK_Table10_Table1", "Table1", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for wormtestModel.efTable2 in the schema.
'''</summary>
'''<KeyProperties>
'''id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="wormtestModel", Name:="efTable2"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class efTable2
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new efTable2 object.
    '''</summary>
    '''<param name="id">Initial value of id.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateefTable2(ByVal id As Integer) As efTable2
        Dim efTable2 As efTable2 = New efTable2()
        efTable2.id = id
        Return efTable2
    End Function
    '''<summary>
    '''There are no comments for property id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property id() As Integer
        Get
            Return Me._id
        End Get
        Set
            Me.OnidChanging(value)
            Me.ReportPropertyChanging("id")
            Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("id")
            Me.OnidChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _id As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanged()
        End Sub
    '''<summary>
    '''There are no comments for property blob in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property blob() As Byte()
        Get
            Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._blob)
        End Get
        Set
            Me.OnblobChanging(value)
            Me.ReportPropertyChanging("blob")
            Me._blob = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("blob")
            Me.OnblobChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _blob() As Byte
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnblobChanging(ByVal value() As Byte)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnblobChanged()
        End Sub
    '''<summary>
    '''There are no comments for property m in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property m() As Global.System.Nullable(Of Decimal)
        Get
            Return Me._m
        End Get
        Set
            Me.OnmChanging(value)
            Me.ReportPropertyChanging("m")
            Me._m = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("m")
            Me.OnmChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _m As Global.System.Nullable(Of Decimal)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnmChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnmChanged()
        End Sub
    '''<summary>
    '''There are no comments for property dt2 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property dt2() As Global.System.Nullable(Of Date)
        Get
            Return Me._dt2
        End Get
        Set
            Me.Ondt2Changing(value)
            Me.ReportPropertyChanging("dt2")
            Me._dt2 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("dt2")
            Me.Ondt2Changed
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _dt2 As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Ondt2Changing(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Ondt2Changed()
        End Sub
    '''<summary>
    '''There are no comments for Table1 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Table2_Table2", "Table1"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table1() As efTable1
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Table2_Table2", "Table1").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Table2_Table2", "Table1").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table1 in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table1Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of efTable1)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Table2_Table2", "Table1")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of efTable1)("wormtestModel.FK_Table2_Table2", "Table1", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Table_Table2", "Table"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table() As efTable
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable)("wormtestModel.FK_Table_Table2", "Table").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable)("wormtestModel.FK_Table_Table2", "Table").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property TableReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of efTable)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable)("wormtestModel.FK_Table_Table2", "Table")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of efTable)("wormtestModel.FK_Table_Table2", "Table", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for wormtestModel.efTable3 in the schema.
'''</summary>
'''<KeyProperties>
'''id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="wormtestModel", Name:="efTable3"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class efTable3
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new efTable3 object.
    '''</summary>
    '''<param name="id">Initial value of id.</param>
    '''<param name="ref_id">Initial value of ref_id.</param>
    '''<param name="code">Initial value of code.</param>
    '''<param name="v">Initial value of v.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateefTable3(ByVal id As Integer, ByVal ref_id As Integer, ByVal code As Byte, ByVal v() As Byte) As efTable3
        Dim efTable3 As efTable3 = New efTable3()
        efTable3.id = id
        efTable3.ref_id = ref_id
        efTable3.code = code
        efTable3.v = v
        Return efTable3
    End Function
    '''<summary>
    '''There are no comments for property id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property id() As Integer
        Get
            Return Me._id
        End Get
        Set
            Me.OnidChanging(value)
            Me.ReportPropertyChanging("id")
            Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("id")
            Me.OnidChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _id As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanged()
        End Sub
    '''<summary>
    '''There are no comments for property ref_id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ref_id() As Integer
        Get
            Return Me._ref_id
        End Get
        Set
            Me.Onref_idChanging(value)
            Me.ReportPropertyChanging("ref_id")
            Me._ref_id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ref_id")
            Me.Onref_idChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ref_id As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onref_idChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub Onref_idChanged()
        End Sub
    '''<summary>
    '''There are no comments for property code in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property code() As Byte
        Get
            Return Me._code
        End Get
        Set
            Me.OncodeChanging(value)
            Me.ReportPropertyChanging("code")
            Me._code = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("code")
            Me.OncodeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _code As Byte
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OncodeChanging(ByVal value As Byte)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OncodeChanged()
        End Sub
    '''<summary>
    '''There are no comments for property v in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property v() As Byte()
        Get
            Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._v)
        End Get
        Set
            Me.OnvChanging(value)
            Me.ReportPropertyChanging("v")
            Me._v = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("v")
            Me.OnvChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _v() As Byte
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnvChanging(ByVal value() As Byte)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnvChanged()
        End Sub
    '''<summary>
    '''There are no comments for property x in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property x() As String
        Get
            Return Me._x
        End Get
        Set
            Me.OnxChanging(value)
            Me.ReportPropertyChanging("x")
            Me._x = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("x")
            Me.OnxChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _x As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnxChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnxChanged()
        End Sub
    '''<summary>
    '''There are no comments for Tables1to3Relation in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Tables1to3Relation_Table3", "Tables1to3Relation"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Tables1to3Relation() As Global.System.Data.Objects.DataClasses.EntityCollection(Of efTables1to3Relation)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of efTables1to3Relation)("wormtestModel.FK_Tables1to3Relation_Table3", "Tables1to3Relation")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of efTables1to3Relation)("wormtestModel.FK_Tables1to3Relation_Table3", "Tables1to3Relation", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for wormtestModel.efTables1to3Relation in the schema.
'''</summary>
'''<KeyProperties>
'''id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="wormtestModel", Name:="efTables1to3Relation"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class efTables1to3Relation
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new efTables1to3Relation object.
    '''</summary>
    '''<param name="id">Initial value of id.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateefTables1to3Relation(ByVal id As Integer) As efTables1to3Relation
        Dim efTables1to3Relation As efTables1to3Relation = New efTables1to3Relation()
        efTables1to3Relation.id = id
        Return efTables1to3Relation
    End Function
    '''<summary>
    '''There are no comments for property id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property id() As Integer
        Get
            Return Me._id
        End Get
        Set
            Me.OnidChanging(value)
            Me.ReportPropertyChanging("id")
            Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("id")
            Me.OnidChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _id As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanged()
        End Sub
    '''<summary>
    '''There are no comments for property name in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property name() As String
        Get
            Return Me._name
        End Get
        Set
            Me.OnnameChanging(value)
            Me.ReportPropertyChanging("name")
            Me._name = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("name")
            Me.OnnameChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _name As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnameChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnnameChanged()
        End Sub
    '''<summary>
    '''There are no comments for Table1 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Tables1to3Relation_Table1", "Table1"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table1() As efTable1
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Tables1to3Relation_Table1", "Table1").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Tables1to3Relation_Table1", "Table1").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table1 in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table1Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of efTable1)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable1)("wormtestModel.FK_Tables1to3Relation_Table1", "Table1")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of efTable1)("wormtestModel.FK_Tables1to3Relation_Table1", "Table1", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table3 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Tables1to3Relation_Table3", "Table3"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table3() As efTable3
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable3)("wormtestModel.FK_Tables1to3Relation_Table3", "Table3").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable3)("wormtestModel.FK_Tables1to3Relation_Table3", "Table3").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table3 in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table3Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of efTable3)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable3)("wormtestModel.FK_Tables1to3Relation_Table3", "Table3")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of efTable3)("wormtestModel.FK_Tables1to3Relation_Table3", "Table3", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for wormtestModel.efTable in the schema.
'''</summary>
'''<KeyProperties>
'''id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="wormtestModel", Name:="efTable"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class efTable
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new efTable object.
    '''</summary>
    '''<param name="id">Initial value of id.</param>
    '''<param name="uq">Initial value of uq.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateefTable(ByVal id As Integer, ByVal uq As Global.System.Guid) As efTable
        Dim efTable As efTable = New efTable()
        efTable.id = id
        efTable.uq = uq
        Return efTable
    End Function
    '''<summary>
    '''There are no comments for property id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property id() As Integer
        Get
            Return Me._id
        End Get
        Set
            Me.OnidChanging(value)
            Me.ReportPropertyChanging("id")
            Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("id")
            Me.OnidChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _id As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnidChanged()
        End Sub
    '''<summary>
    '''There are no comments for property col in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property col() As Global.System.Nullable(Of Boolean)
        Get
            Return Me._col
        End Get
        Set
            Me.OncolChanging(value)
            Me.ReportPropertyChanging("col")
            Me._col = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("col")
            Me.OncolChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _col As Global.System.Nullable(Of Boolean)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OncolChanging(ByVal value As Global.System.Nullable(Of Boolean))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OncolChanged()
        End Sub
    '''<summary>
    '''There are no comments for property uq in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property uq() As Global.System.Guid
        Get
            Return Me._uq
        End Get
        Set
            Me.OnuqChanging(value)
            Me.ReportPropertyChanging("uq")
            Me._uq = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("uq")
            Me.OnuqChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _uq As Global.System.Guid
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnuqChanging(ByVal value As Global.System.Guid)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnuqChanged()
        End Sub
    '''<summary>
    '''There are no comments for Table2 in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("wormtestModel", "FK_Table_Table2", "Table2"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table2() As efTable2
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable2)("wormtestModel.FK_Table_Table2", "Table2").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable2)("wormtestModel.FK_Table_Table2", "Table2").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Table2 in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Table2Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of efTable2)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of efTable2)("wormtestModel.FK_Table_Table2", "Table2")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of efTable2)("wormtestModel.FK_Table_Table2", "Table2", value)
            End If
        End Set
    End Property
End Class
