'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("6bc31906-304e-41cd-8f22-1aa6f206e629"),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_Table_Table2", "Table2", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.Table2), "Table", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Model.Table)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_Table10_Table1", "Table1", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Model.Table1), "Table10", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.Table10)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_Table2_Table2", "Table1", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Model.Table1), "Table2", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.Table2)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_Tables1to3Relation_Table1", "Table1", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.Table1), "Tables1to3Relation", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.Tables1to3Relation)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("Model", "FK_Tables1to3Relation_Table3", "Table3", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Model.Table3), "Tables1to3Relation", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Model.Tables1to3Relation))> 

'Original file name:
'Generation date: 20.05.2008 23:05:58
Namespace Model
    '''<summary>
    '''There are no comments for Entities in the schema.
    '''</summary>
    Partial Public Class Entities
        Inherits Global.System.Data.Objects.ObjectContext
        '''<summary>
        '''Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        '''</summary>
        Public Sub New()
            MyBase.New("name=Entities", "Entities")
        End Sub
        '''<summary>
        '''Initialize a new Entities object.
        '''</summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "Entities")
        End Sub
        '''<summary>
        '''Initialize a new Entities object.
        '''</summary>
        Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
            MyBase.New(connection, "Entities")
        End Sub
        '''<summary>
        '''There are no comments for Table in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Table() As Global.System.Data.Objects.ObjectQuery(Of Table)
            Get
                If (Me._Table Is Nothing) Then
                    Me._Table = MyBase.CreateQuery(Of Table)("[Table]")
                End If
                Return Me._Table
            End Get
        End Property
        Private _Table As Global.System.Data.Objects.ObjectQuery(Of Table)
        '''<summary>
        '''There are no comments for Table1 in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Table1() As Global.System.Data.Objects.ObjectQuery(Of Table1)
            Get
                If (Me._Table1 Is Nothing) Then
                    Me._Table1 = MyBase.CreateQuery(Of Table1)("[Table1]")
                End If
                Return Me._Table1
            End Get
        End Property
        Private _Table1 As Global.System.Data.Objects.ObjectQuery(Of Table1)
        '''<summary>
        '''There are no comments for Table10 in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Table10() As Global.System.Data.Objects.ObjectQuery(Of Table10)
            Get
                If (Me._Table10 Is Nothing) Then
                    Me._Table10 = MyBase.CreateQuery(Of Table10)("[Table10]")
                End If
                Return Me._Table10
            End Get
        End Property
        Private _Table10 As Global.System.Data.Objects.ObjectQuery(Of Table10)
        '''<summary>
        '''There are no comments for Table1to1 in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Table1to1() As Global.System.Data.Objects.ObjectQuery(Of Table1to1)
            Get
                If (Me._Table1to1 Is Nothing) Then
                    Me._Table1to1 = MyBase.CreateQuery(Of Table1to1)("[Table1to1]")
                End If
                Return Me._Table1to1
            End Get
        End Property
        Private _Table1to1 As Global.System.Data.Objects.ObjectQuery(Of Table1to1)
        '''<summary>
        '''There are no comments for Table2 in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Table2() As Global.System.Data.Objects.ObjectQuery(Of Table2)
            Get
                If (Me._Table2 Is Nothing) Then
                    Me._Table2 = MyBase.CreateQuery(Of Table2)("[Table2]")
                End If
                Return Me._Table2
            End Get
        End Property
        Private _Table2 As Global.System.Data.Objects.ObjectQuery(Of Table2)
        '''<summary>
        '''There are no comments for Table3 in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Table3() As Global.System.Data.Objects.ObjectQuery(Of Table3)
            Get
                If (Me._Table3 Is Nothing) Then
                    Me._Table3 = MyBase.CreateQuery(Of Table3)("[Table3]")
                End If
                Return Me._Table3
            End Get
        End Property
        Private _Table3 As Global.System.Data.Objects.ObjectQuery(Of Table3)
        '''<summary>
        '''There are no comments for Tables1to3Relation in the schema.
        '''</summary>
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Tables1to3Relation() As Global.System.Data.Objects.ObjectQuery(Of Tables1to3Relation)
            Get
                If (Me._Tables1to3Relation Is Nothing) Then
                    Me._Tables1to3Relation = MyBase.CreateQuery(Of Tables1to3Relation)("[Tables1to3Relation]")
                End If
                Return Me._Tables1to3Relation
            End Get
        End Property
        Private _Tables1to3Relation As Global.System.Data.Objects.ObjectQuery(Of Tables1to3Relation)
        '''<summary>
        '''There are no comments for Table in the schema.
        '''</summary>
        Public Sub AddToTable(ByVal table As Table)
            MyBase.AddObject("Table", table)
        End Sub
        '''<summary>
        '''There are no comments for Table1 in the schema.
        '''</summary>
        Public Sub AddToTable1(ByVal table1 As Table1)
            MyBase.AddObject("Table1", table1)
        End Sub
        '''<summary>
        '''There are no comments for Table10 in the schema.
        '''</summary>
        Public Sub AddToTable10(ByVal table10 As Table10)
            MyBase.AddObject("Table10", table10)
        End Sub
        '''<summary>
        '''There are no comments for Table1to1 in the schema.
        '''</summary>
        Public Sub AddToTable1to1(ByVal table1to1 As Table1to1)
            MyBase.AddObject("Table1to1", table1to1)
        End Sub
        '''<summary>
        '''There are no comments for Table2 in the schema.
        '''</summary>
        Public Sub AddToTable2(ByVal table2 As Table2)
            MyBase.AddObject("Table2", table2)
        End Sub
        '''<summary>
        '''There are no comments for Table3 in the schema.
        '''</summary>
        Public Sub AddToTable3(ByVal table3 As Table3)
            MyBase.AddObject("Table3", table3)
        End Sub
        '''<summary>
        '''There are no comments for Tables1to3Relation in the schema.
        '''</summary>
        Public Sub AddToTables1to3Relation(ByVal tables1to3Relation As Tables1to3Relation)
            MyBase.AddObject("Tables1to3Relation", tables1to3Relation)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Model.Table in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Table"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(),  _
     Global.System.Serializable()>  _
    Partial Public Class Table
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Table object.
        '''</summary>
        '''<param name="ID">Initial value of id.</param>
        '''<param name="uq">Initial value of uq.</param>
        Public Shared Function CreateTable(ByVal ID As Integer, ByVal uq As Global.System.Guid) As Table
            Dim table As Table = New Table
            table.id = ID
            table.uq = uq
            Return table
        End Function
        '''<summary>
        '''There are no comments for Property id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me.OnidChanging(value)
                Me.ReportPropertyChanging("id")
                Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id")
                Me.OnidChanged
            End Set
        End Property
        Private _id As Integer
        Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property col in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property col() As Global.System.Nullable(Of Boolean)
            Get
                Return Me._col
            End Get
            Set
                Me.OncolChanging(value)
                Me.ReportPropertyChanging("col")
                Me._col = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("col")
                Me.OncolChanged
            End Set
        End Property
        Private _col As Global.System.Nullable(Of Boolean)
        Partial Private Sub OncolChanging(ByVal value As Global.System.Nullable(Of Boolean))
        End Sub
        Partial Private Sub OncolChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property uq in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property uq() As Global.System.Guid
            Get
                Return Me._uq
            End Get
            Set
                Me.OnuqChanging(value)
                Me.ReportPropertyChanging("uq")
                Me._uq = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("uq")
                Me.OnuqChanged
            End Set
        End Property
        Private _uq As Global.System.Guid
        Partial Private Sub OnuqChanging(ByVal value As Global.System.Guid)
        End Sub
        Partial Private Sub OnuqChanged()
        End Sub
        '''<summary>
        '''There are no comments for Table2 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Table_Table2", "Table2"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table2() As Table2
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table2)("Model.FK_Table_Table2", "Table2").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table2)("Model.FK_Table_Table2", "Table2").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Table2 in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table2Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Table2)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table2)("Model.FK_Table_Table2", "Table2")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Table2)("Model.FK_Table_Table2", "Table2", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for Model.Table1 in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Table1"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(),  _
     Global.System.Serializable()>  _
    Partial Public Class Table1
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Table1 object.
        '''</summary>
        '''<param name="ID">Initial value of id.</param>
        '''<param name="dt">Initial value of dt.</param>
        Public Shared Function CreateTable1(ByVal ID As Integer, ByVal dt As Date) As Table1
            Dim table1 As Table1 = New Table1
            table1.id = ID
            table1.dt = dt
            Return table1
        End Function
        '''<summary>
        '''There are no comments for Property id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me.OnidChanging(value)
                Me.ReportPropertyChanging("id")
                Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id")
                Me.OnidChanged
            End Set
        End Property
        Private _id As Integer
        Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property name in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property name() As String
            Get
                Return Me._name
            End Get
            Set
                Me.OnnameChanging(value)
                Me.ReportPropertyChanging("name")
                Me._name = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50)
                Me.ReportPropertyChanged("name")
                Me.OnnameChanged
            End Set
        End Property
        Private _name As String
        Partial Private Sub OnnameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnnameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property code in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property code() As Global.System.Nullable(Of Integer)
            Get
                Return Me._code
            End Get
            Set
                Me.OncodeChanging(value)
                Me.ReportPropertyChanging("code")
                Me._code = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("code")
                Me.OncodeChanged
            End Set
        End Property
        Private _code As Global.System.Nullable(Of Integer)
        Partial Private Sub OncodeChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OncodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property enum in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [enum]() As Global.System.Nullable(Of Byte)
            Get
                Return Me._enum
            End Get
            Set
                Me.OnenumChanging(value)
                Me.ReportPropertyChanging("enum")
                Me._enum = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("enum")
                Me.OnenumChanged
            End Set
        End Property
        Private _enum As Global.System.Nullable(Of Byte)
        Partial Private Sub OnenumChanging(ByVal value As Global.System.Nullable(Of Byte))
        End Sub
        Partial Private Sub OnenumChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property enum_str in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property enum_str() As String
            Get
                Return Me._enum_str
            End Get
            Set
                Me.Onenum_strChanging(value)
                Me.ReportPropertyChanging("enum_str")
                Me._enum_str = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50)
                Me.ReportPropertyChanged("enum_str")
                Me.Onenum_strChanged
            End Set
        End Property
        Private _enum_str As String
        Partial Private Sub Onenum_strChanging(ByVal value As String)
        End Sub
        Partial Private Sub Onenum_strChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property dt in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dt() As Date
            Get
                Return Me._dt
            End Get
            Set
                Me.OndtChanging(value)
                Me.ReportPropertyChanging("dt")
                Me._dt = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, Global.System.DateTimeKind.Unspecified, true)
                Me.ReportPropertyChanged("dt")
                Me.OndtChanged
            End Set
        End Property
        Private _dt As Date
        Partial Private Sub OndtChanging(ByVal value As Date)
        End Sub
        Partial Private Sub OndtChanged()
        End Sub
        '''<summary>
        '''There are no comments for Table10 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Table10_Table1", "Table10"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Table10() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Table10)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Table10)("Model.FK_Table10_Table1", "Table10")
            End Get
        End Property
        '''<summary>
        '''There are no comments for Table2 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Table2_Table2", "Table2"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Table2() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Table2)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Table2)("Model.FK_Table2_Table2", "Table2")
            End Get
        End Property
        '''<summary>
        '''There are no comments for Tables1to3Relation in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Tables1to3Relation_Table1", "Tables1to3Relation"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Tables1to3Relation() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Tables1to3Relation)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Tables1to3Relation)("Model.FK_Tables1to3Relation_Table1", "Tables1to3Relation")
            End Get
        End Property
    End Class
    '''<summary>
    '''There are no comments for Model.Table10 in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Table10"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(),  _
     Global.System.Serializable()>  _
    Partial Public Class Table10
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Table10 object.
        '''</summary>
        '''<param name="ID">Initial value of id.</param>
        Public Shared Function CreateTable10(ByVal ID As Integer) As Table10
            Dim table10 As Table10 = New Table10
            table10.id = ID
            Return table10
        End Function
        '''<summary>
        '''There are no comments for Property id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me.OnidChanging(value)
                Me.ReportPropertyChanging("id")
                Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id")
                Me.OnidChanged
            End Set
        End Property
        Private _id As Integer
        Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Table1 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Table10_Table1", "Table1"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table1() As Table1
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Table10_Table1", "Table1").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Table10_Table1", "Table1").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Table1 in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table1Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Table1)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Table10_Table1", "Table1")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Table1)("Model.FK_Table10_Table1", "Table1", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for Model.Table1to1 in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Table1to1"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(),  _
     Global.System.Serializable()>  _
    Partial Public Class Table1to1
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Table1to1 object.
        '''</summary>
        '''<param name="ID">Initial value of id.</param>
        '''<param name="table1">Initial value of table1.</param>
        '''<param name="table1_back">Initial value of table1_back.</param>
        Public Shared Function CreateTable1to1(ByVal ID As Integer, ByVal table1 As Integer, ByVal table1_back As Integer) As Table1to1
            Dim table1to1 As Table1to1 = New Table1to1
            table1to1.id = ID
            table1to1.table1 = table1
            table1to1.table1_back = table1_back
            Return table1to1
        End Function
        '''<summary>
        '''There are no comments for Property id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me.OnidChanging(value)
                Me.ReportPropertyChanging("id")
                Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id")
                Me.OnidChanged
            End Set
        End Property
        Private _id As Integer
        Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property table1 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property table1() As Integer
            Get
                Return Me._table1
            End Get
            Set
                Me.Ontable1Changing(value)
                Me.ReportPropertyChanging("table1")
                Me._table1 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("table1")
                Me.Ontable1Changed
            End Set
        End Property
        Private _table1 As Integer
        Partial Private Sub Ontable1Changing(ByVal value As Integer)
        End Sub
        Partial Private Sub Ontable1Changed()
        End Sub
        '''<summary>
        '''There are no comments for Property table1_back in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property table1_back() As Integer
            Get
                Return Me._table1_back
            End Get
            Set
                Me.Ontable1_backChanging(value)
                Me.ReportPropertyChanging("table1_back")
                Me._table1_back = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("table1_back")
                Me.Ontable1_backChanged
            End Set
        End Property
        Private _table1_back As Integer
        Partial Private Sub Ontable1_backChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub Ontable1_backChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property k in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property k() As String
            Get
                Return Me._k
            End Get
            Set
                Me.OnkChanging(value)
                Me.ReportPropertyChanging("k")
                Me._k = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50)
                Me.ReportPropertyChanged("k")
                Me.OnkChanged
            End Set
        End Property
        Private _k As String
        Partial Private Sub OnkChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnkChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for Model.Table2 in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Table2"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(),  _
     Global.System.Serializable()>  _
    Partial Public Class Table2
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Table2 object.
        '''</summary>
        '''<param name="ID">Initial value of id.</param>
        Public Shared Function CreateTable2(ByVal ID As Integer) As Table2
            Dim table2 As Table2 = New Table2
            table2.id = ID
            Return table2
        End Function
        '''<summary>
        '''There are no comments for Property id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me.OnidChanging(value)
                Me.ReportPropertyChanging("id")
                Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id")
                Me.OnidChanged
            End Set
        End Property
        Private _id As Integer
        Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property blob in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property blob() As Byte()
            Get
                Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._blob)
            End Get
            Set
                Me.OnblobChanging(value)
                Me.ReportPropertyChanging("blob")
                Me._blob = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647)
                Me.ReportPropertyChanged("blob")
                Me.OnblobChanged
            End Set
        End Property
        Private _blob() As Byte
        Partial Private Sub OnblobChanging(ByVal value() As Byte)
        End Sub
        Partial Private Sub OnblobChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property m in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property m() As Global.System.Nullable(Of Decimal)
            Get
                Return Me._m
            End Get
            Set
                Me.OnmChanging(value)
                Me.ReportPropertyChanging("m")
                Me._m = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, 19, 4)
                Me.ReportPropertyChanged("m")
                Me.OnmChanged
            End Set
        End Property
        Private _m As Global.System.Nullable(Of Decimal)
        Partial Private Sub OnmChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
        Partial Private Sub OnmChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property dt2 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dt2() As Global.System.Nullable(Of Date)
            Get
                Return Me._dt2
            End Get
            Set
                Me.Ondt2Changing(value)
                Me.ReportPropertyChanging("dt2")
                Me._dt2 = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, Global.System.DateTimeKind.Unspecified, true)
                Me.ReportPropertyChanged("dt2")
                Me.Ondt2Changed
            End Set
        End Property
        Private _dt2 As Global.System.Nullable(Of Date)
        Partial Private Sub Ondt2Changing(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub Ondt2Changed()
        End Sub
        '''<summary>
        '''There are no comments for Table in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Table_Table2", "Table"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table() As Table
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table)("Model.FK_Table_Table2", "Table").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table)("Model.FK_Table_Table2", "Table").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Table in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property TableReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Table)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table)("Model.FK_Table_Table2", "Table")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Table)("Model.FK_Table_Table2", "Table", value)
                End If
            End Set
        End Property
        '''<summary>
        '''There are no comments for Table1 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Table2_Table2", "Table1"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table1() As Table1
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Table2_Table2", "Table1").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Table2_Table2", "Table1").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Table1 in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table1Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Table1)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Table2_Table2", "Table1")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Table1)("Model.FK_Table2_Table2", "Table1", value)
                End If
            End Set
        End Property
    End Class
    '''<summary>
    '''There are no comments for Model.Table3 in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Table3"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(),  _
     Global.System.Serializable()>  _
    Partial Public Class Table3
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Table3 object.
        '''</summary>
        '''<param name="ID">Initial value of id.</param>
        '''<param name="ref_id">Initial value of ref_id.</param>
        '''<param name="code">Initial value of code.</param>
        '''<param name="v">Initial value of v.</param>
        Public Shared Function CreateTable3(ByVal ID As Integer, ByVal ref_id As Integer, ByVal code As Byte, ByVal v() As Byte) As Table3
            Dim table3 As Table3 = New Table3
            table3.id = ID
            table3.ref_id = ref_id
            table3.code = code
            table3.v = v
            Return table3
        End Function
        '''<summary>
        '''There are no comments for Property id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me.OnidChanging(value)
                Me.ReportPropertyChanging("id")
                Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id")
                Me.OnidChanged
            End Set
        End Property
        Private _id As Integer
        Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ref_id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ref_id() As Integer
            Get
                Return Me._ref_id
            End Get
            Set
                Me.Onref_idChanging(value)
                Me.ReportPropertyChanging("ref_id")
                Me._ref_id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("ref_id")
                Me.Onref_idChanged
            End Set
        End Property
        Private _ref_id As Integer
        Partial Private Sub Onref_idChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub Onref_idChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property code in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property code() As Byte
            Get
                Return Me._code
            End Get
            Set
                Me.OncodeChanging(value)
                Me.ReportPropertyChanging("code")
                Me._code = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("code")
                Me.OncodeChanged
            End Set
        End Property
        Private _code As Byte
        Partial Private Sub OncodeChanging(ByVal value As Byte)
        End Sub
        Partial Private Sub OncodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property v in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property v() As Byte()
            Get
                Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._v)
            End Get
            Set
                Me.OnvChanging(value)
                Me.ReportPropertyChanging("v")
                Me._v = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 8)
                Me.ReportPropertyChanged("v")
                Me.OnvChanged
            End Set
        End Property
        Private _v() As Byte
        Partial Private Sub OnvChanging(ByVal value() As Byte)
        End Sub
        Partial Private Sub OnvChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property x in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property x() As String
            Get
                Return Me._x
            End Get
            Set
                Me.OnxChanging(value)
                Me.ReportPropertyChanging("x")
                Me._x = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 1073741823)
                Me.ReportPropertyChanged("x")
                Me.OnxChanged
            End Set
        End Property
        Private _x As String
        Partial Private Sub OnxChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnxChanged()
        End Sub
        '''<summary>
        '''There are no comments for Tables1to3Relation in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Tables1to3Relation_Table3", "Tables1to3Relation"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public ReadOnly Property Tables1to3Relation() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Tables1to3Relation)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Tables1to3Relation)("Model.FK_Tables1to3Relation_Table3", "Tables1to3Relation")
            End Get
        End Property
    End Class
    '''<summary>
    '''There are no comments for Model.Tables1to3Relation in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="Model", Name:="Tables1to3Relation"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(),  _
     Global.System.Serializable()>  _
    Partial Public Class Tables1to3Relation
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new Tables1to3Relation object.
        '''</summary>
        '''<param name="ID">Initial value of id.</param>
        Public Shared Function CreateTables1to3Relation(ByVal ID As Integer) As Tables1to3Relation
            Dim tables1to3Relation As Tables1to3Relation = New Tables1to3Relation
            tables1to3Relation.id = ID
            Return tables1to3Relation
        End Function
        '''<summary>
        '''There are no comments for Property id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me.OnidChanging(value)
                Me.ReportPropertyChanging("id")
                Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id")
                Me.OnidChanged
            End Set
        End Property
        Private _id As Integer
        Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property name in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property name() As String
            Get
                Return Me._name
            End Get
            Set
                Me.OnnameChanging(value)
                Me.ReportPropertyChanging("name")
                Me._name = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50)
                Me.ReportPropertyChanged("name")
                Me.OnnameChanged
            End Set
        End Property
        Private _name As String
        Partial Private Sub OnnameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnnameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Table1 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Tables1to3Relation_Table1", "Table1"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table1() As Table1
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Tables1to3Relation_Table1", "Table1").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Tables1to3Relation_Table1", "Table1").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Table1 in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table1Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Table1)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table1)("Model.FK_Tables1to3Relation_Table1", "Table1")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Table1)("Model.FK_Tables1to3Relation_Table1", "Table1", value)
                End If
            End Set
        End Property
        '''<summary>
        '''There are no comments for Table3 in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Model", "FK_Tables1to3Relation_Table3", "Table3"),  _
         Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
         Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table3() As Table3
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table3)("Model.FK_Tables1to3Relation_Table3", "Table3").Value
            End Get
            Set
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table3)("Model.FK_Tables1to3Relation_Table3", "Table3").Value = value
            End Set
        End Property
        '''<summary>
        '''There are no comments for Table3 in the schema.
        '''</summary>
        <Global.System.Runtime.Serialization.DataMemberAttribute(),  _
         Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property Table3Reference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Table3)
            Get
                Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Table3)("Model.FK_Tables1to3Relation_Table3", "Table3")
            End Get
            Set
                If (Not (value) Is Nothing) Then
                    CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Table3)("Model.FK_Tables1to3Relation_Table3", "Table3", value)
                End If
            End Set
        End Property
    End Class
End Namespace
